name: fastprop
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20230802.0=h313beb8_2
  - alembic=1.13.2=pyhd8ed1ab_0
  - anyio=4.2.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - arrow=1.2.3=py311hca03da5_1
  - arrow-cpp=14.0.2=hc7aafb3_1
  - astartes=1.3.0=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - aws-c-auth=0.6.21=h284e69b_0
  - aws-c-cal=0.5.20=h7a1267a_3
  - aws-c-common=0.8.5=h1a8c8d9_0
  - aws-c-compression=0.2.16=ha56e2a8_0
  - aws-c-event-stream=0.2.15=h5f184b6_11
  - aws-c-http=0.6.27=hb329ca4_3
  - aws-c-io=0.13.11=h2ec9475_2
  - aws-c-mqtt=0.7.13=h5377834_9
  - aws-c-s3=0.2.1=hbdbf862_0
  - aws-c-sdkutils=0.1.7=ha56e2a8_0
  - aws-checksums=0.1.13=ha56e2a8_5
  - aws-crt-cpp=0.18.16=h14806b3_2
  - aws-sdk-cpp=1.10.55=h313beb8_0
  - babel=2.11.0=py311hca03da5_0
  - backoff=2.2.1=py311hca03da5_1
  - banal=1.0.6=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blessed=1.20.0=py311hca03da5_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - boto3=1.34.154=py311hca03da5_0
  - botocore=1.34.154=py311hca03da5_0
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.32.3=h99b78c6_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cairo=1.16.0=h302bd0f_5
  - cffi=1.16.0=py311h80987f9_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.2.1=py311hca03da5_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - croniter=1.3.7=py311hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - dataset=1.5.2=pyhd8ed1ab_0
  - dateutils=0.6.12=py311hca03da5_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deepdiff=7.0.1=py311hb6e6a13_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h313beb8_0
  - fastapi=0.103.0=py311hca03da5_0
  - filelock=3.13.1=py311hca03da5_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.3.1=py311hca03da5_0
  - gettext=0.21.0=h13f89a0_1
  - gflags=2.2.2=hc88da5d_1004
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - glog=0.5.0=h5c6a83d_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - greenlet=3.0.1=py311h313beb8_0
  - grpc-cpp=1.48.2=hc60591f_4
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - gtest=1.14.0=h48ca7d4_1
  - h11=0.14.0=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - inquirer=3.1.4=py311hca03da5_0
  - ipykernel=6.28.0=py311hca03da5_0
  - ipython=8.20.0=py311hca03da5_0
  - ipywidgets=8.1.2=py311hca03da5_0
  - itsdangerous=2.2.0=py311hca03da5_0
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.3=py311hca03da5_0
  - jmespath=1.0.1=py311hca03da5_0
  - joblib=1.2.0=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter=1.0.0=py311hca03da5_9
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=8.6.0=py311hca03da5_0
  - jupyter_console=6.6.3=py311hca03da5_0
  - jupyter_core=5.5.0=py311hca03da5_0
  - jupyter_events=0.8.0=py311hca03da5_0
  - jupyter_server=2.10.0=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab=4.0.11=py311hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311hca03da5_0
  - jupyterlab_widgets=3.0.10=py311hca03da5_0
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h1a28f6b_2
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.10.0=h7a5bd25_2
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxgboost=1.7.4=cpu_h13cf1d8_0
  - libxml2=2.10.4=h0b34f26_2
  - libzlib=1.2.13=hfb2fe0b_6
  - lightgbm=4.3.0=py311h313beb8_0
  - lightning=2.0.9.post0=py311hca03da5_0
  - lightning-cloud=0.5.57=py311hca03da5_0
  - lightning-utilities=0.9.0=py311hca03da5_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - mako=1.3.5=pyhd8ed1ab_0
  - matplotlib=3.8.4=py311hca03da5_0
  - matplotlib-base=3.8.4=py311h7aedaa7_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mistune=2.0.4=py311hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - networkx=3.3=py311hca03da5_0
  - notebook=7.0.8=py311hca03da5_0
  - notebook-shim=0.2.3=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.5.0=h81ee809_0
  - orc=1.7.4=hdca1487_1
  - ordered-set=4.1.0=py311hca03da5_0
  - orjson=3.9.15=py311hc9796cf_0
  - overrides=7.4.0=py311hca03da5_0
  - pandas=2.2.1=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=1.0.1=pyhff2d567_0
  - pcre2=10.42=hb066dcc_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=23.3.1=py311hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - ply=3.11=py311hca03da5_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.7.4=cpu_py311h71cf02c_0
  - pyarrow=14.0.2=py311ha07b5f9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py311h80987f9_1
  - pyjwt=2.8.0=py311hca03da5_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pyqt=5.15.10=py311h313beb8_0
  - pyqt5-sip=12.13.0=py311h80987f9_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - python-multipart=0.0.9=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=5_cp311
  - pytorch=2.3.0=gpu_mps_py311hc07fac7_100
  - pytorch-lightning=2.3.0=py311hca03da5_0
  - pytz=2023.3.post1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - qt-main=5.15.2=h0917680_10
  - qtconsole=5.5.1=py311hca03da5_0
  - qtpy=2.4.1=py311hca03da5_0
  - re2=2022.04.01=h6b3803e_0
  - readchar=4.0.5=py311hca03da5_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - s3transfer=0.10.1=py311hca03da5_0
  - scipy=1.12.0=py311hc76d9b0_0
  - send2trash=1.8.2=py311hca03da5_0
  - sip=6.7.12=py311h313beb8_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlalchemy=2.0.30=py311h80987f9_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - starlette=0.27.0=py311hca03da5_0
  - starsessions=1.3.0=py311hca03da5_0
  - statsmodels=0.14.4=py311h0f07fe1_0
  - sympy=1.12=py311hca03da5_0
  - tabulate=0.9.0=py311hca03da5_0
  - terminado=0.17.1=py311hca03da5_0
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchmetrics=1.4.0.post0=py311hca03da5_0
  - tornado=6.3.3=py311h80987f9_0
  - tqdm=4.66.4=py311hb6e6a13_0
  - traitlets=5.7.1=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - utf8proc=2.6.1=h80987f9_1
  - uvicorn=0.20.0=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=0.58.0=py311hca03da5_4
  - websockets=10.4=py311h80987f9_1
  - widgetsnbextension=4.0.10=py311hca03da5_0
  - xgboost=1.7.4=cpu_py311hb082c4a_0
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.5=hd90d995_0
  - pip:
      - absl-py==2.3.1
      - adabound==0.0.5
      - aimsim==2.2.2
      - aimsim-core==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - astunparse==1.6.3
      - captum==0.8.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - darkdetect==0.8.0
      - dill==0.3.8
      - et-xmlfile==1.1.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - idna==3.10
      - imageio==2.37.0
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - keras==3.10.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lion-pytorch==0.2.3
      - llvmlite==0.44.0
      - lxml==6.0.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mhfp==1.9.6
      - ml-dtypes==0.5.1
      - mordredcommunity==2.0.6
      - multidict==6.4.3
      - multiprocess==0.70.16
      - namex==0.1.0
      - numba==0.61.2
      - numpy==1.26.4
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - optuna==4.2.1
      - packaging==24.2
      - padelpy==0.1.16
      - pillow==10.3.0
      - plotly==5.24.0
      - polars==1.4.1
      - propcache==0.3.1
      - protobuf==5.29.5
      - pubchempy==1.0.4
      - pygments==2.19.2
      - pymic==0.5.0
      - rdkit==2024.3.5
      - rdkit-pypi==2022.9.5
      - requests==2.32.4
      - rich==14.0.0
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scikit-learn-extra==0.3.0
      - seaborn==0.13.2
      - setuptools==80.9.0
      - shap==0.48.0
      - simpleitk==2.4.1
      - six==1.17.0
      - slicer==0.0.8
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.5.0
      - tifffile==2025.3.30
      - typing-extensions==4.14.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==24.8.0
      - werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.2
      - xeus-python==0.15.12
      - xeus-python-shell==0.5.0
      - yarl==1.20.0
prefix: /opt/anaconda3/envs/fastprop
